spring:
  application:
    name: rsvp-system
  datasource:
    url: jdbc:postgresql://localhost:5432/tax
    username: postgres
    password: p@ssw0rd
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
    change-log: classpath:db/db.changelog.yaml
server:
  port: 7878
  servlet:
    context-path: /tax/api
logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %thread ${PID} [%X{correlationId}] %-5level %logger{36} - %class{1} - %msg%n"