spring:
  application:
    name: tax-calc
server:
  port: 7878
  servlet:
    context-path: /tax
logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %thread ${PID} [%X{correlationId}] %-5level %logger{36} - %class{1} - %msg%n"